In [1]:
from node import *
import pulp as plp
import numpy as np
import pandas as pd

In [9]:
d=node('d',[])
b=node('b',[d])
c=node('c',[])
a=node('a',[b,c]);
f=node('f',[])
g=node('g',[])
e=node('e',[f,g])

In [61]:
set_J

range(0, 3)

In [10]:
n = 4
m = 3
set_I = range(0, n)
set_J = range(0, m)
c = {(i,j): 1 for i in set_I for j in set_J}

In [11]:
def find_path_root(now,dfs,path,dfs_node,f):
    now.path=path.copy();
    now.f=f
    now.dfs=dfs;
    path.append(now);
    dfs_node.append(now);
    for i in now.son:
        dfs=find_path_root(i,dfs+1,path,dfs_node,now);
        
    path.remove(now)
    now.num_son = dfs-now.dfs;
    return dfs

In [12]:
dfs_node1=[]
dfs_node2=[]
find_path_root(a,0,[],dfs_node1,a)
find_path_root(e,0,[],dfs_node2,e)

2

In [18]:
i, j = np.meshgrid(np.arange(n, dtype=int), np.arange(m, dtype=int))
i,j

(array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]),
 array([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2]]))

In [84]:
x_vars  = [[0 for j in set_J] for i in set_I]
s= [[1 for j in set_J] for i in set_I]
x_vars

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [132]:
np.array([x_vars[1][j] for j in set_J]).sum() !=1

True

In [184]:
def search():
    for i in set_I:
        if(np.array([x_vars[i][j] for j in set_J]).sum()<1):
            return False;
        
    for j in set_J:
        if(np.array([x_vars[i][j] for i in set_I]).sum()<1):
            return False

    for i in dfs_node1:
        for j in dfs_node2:
            son_i = [dfs_node1[k] for k in range(i.dfs,i.dfs+i.num_son)];
            son_j = [dfs_node2[k] for k in range(j.dfs,j.dfs+j.num_son)];
            for k in i.path:
                for l in j.path:
                    if(k==[]or l==[]):
                        continue;
                    
                    # print(i,j,k,l)
                    if(x_vars[k.dfs][j.dfs]+x_vars[i.dfs][l.dfs]+x_vars[k.dfs][l.dfs]<x_vars[i.dfs][j.dfs]):
                        return False;
        for k in i.path:
            for l in son_j:
                if(k==[]or l==[]):
                    continue;
                if(x_vars[i.dfs][j.dfs]+x_vars[k.dfs][l.dfs]>1):
                    return False
        for k in son_i:
            for l in j.path:
                if(k==[]or l==[]):
                    continue;
                if(x_vars[i.dfs][j.dfs]+x_vars[k.dfs][l.dfs]>1):
                    return False;
        
    return True

            

In [185]:
x_vars

[[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [186]:
ans=-1
anslist=x_vars.copy();
for i in range(pow(2,n*m)):
    t=format(i,'0'+str(n*m)+'b')
    for idx,j in enumerate(t):
        x_vars[int(idx/m)][int(idx%m)]=int(j)
    if(search()==True):
        
        if(ans<= (np.array(s)*np.array(x_vars)).sum() ):
            ans= (np.array(s)*np.array(x_vars)).sum()
            anslist= np.array(x_vars)
anslist,ans

(array([[1, 1, 0],
        [1, 1, 0],
        [1, 1, 1],
        [1, 1, 1]]),
 10)

In [187]:
print('SOLUTION:')
for i in range(n*m):
    print('\t\tx_{}_{}={}'.format(int(i/m),int(i%m),anslist[int(i/m)][int(i%m)]) )
print(f'OBJECTIVE VALUE: {ans}')

SOLUTION:
		x_0_0=1
		x_0_1=1
		x_0_2=0
		x_1_0=1
		x_1_1=1
		x_1_2=0
		x_2_0=1
		x_2_1=1
		x_2_2=1
		x_3_0=1
		x_3_1=1
		x_3_2=1
OBJECTIVE VALUE: 10
